### ISSUE TITLE
打包docker镜像，运行无法使用，报错

### ISSUE THREAD

**Issue by vgdebsyxh** [14790897/auto-read-liunxdo#2]
- 使用项目内的Dockerfile构建
- 使用docker-compose启动
- 错误日志
```txt
liunxdo  | /app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/disposable.js:9
liunxdo  | Symbol.dispose ??= Symbol('dispose');
liunxdo  |                ^^^
liunxdo  | 
liunxdo  | SyntaxError: Unexpected token '??='
liunxdo  |     at wrapSafe (internal/modules/cjs/loader.js:1029:16)
liunxdo  |     at Module._compile (internal/modules/cjs/loader.js:1078:27)
liunxdo  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
liunxdo  |     at Module.load (internal/modules/cjs/loader.js:979:32)
liunxdo  |     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
liunxdo  |     at Module.require (internal/modules/cjs/loader.js:1003:19)
liunxdo  |     at require (internal/modules/cjs/helpers.js:107:18)
liunxdo  |     at Object.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:13:25)
liunxdo  |     at Module._compile (internal/modules/cjs/loader.js:1114:14)
liunxdo  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
liunxdo exited with code 1
```

**Comment by 14790897** [comment]
docker我还没弄好呢

vgdebsyxh ***@***.***> 于 2024年4月5日周五 上午10:28写道：

**Comment by 14790897** [comment]
docker好了
