### ISSUE TITLE
linux 运行报错

### ISSUE THREAD

**Issue by lostme01** [14790897/auto-read-liunxdo#7]
root@ubuntu:~/auto_linuxdo# npm install

> puppeteer@22.6.3 postinstall /root/auto_linuxdo/node_modules/puppeteer
> node install.mjs

/root/auto_linuxdo/node_modules/puppeteer/install.mjs:31
  const {downloadBrowser} = await importInstaller();
                            ^^^^^

SyntaxError: await is only valid in async function
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

docker部署起来以后，没有任何日志

**Comment by 14790897** [comment]
升级node版本到最新

**Comment by 14790897** [comment]
docker弄好了

**Comment by lostme01** [comment]
> docker弄好了

没有好，我重新部署了一遍，docker还是没有任何日志

**Comment by lostme01** [comment]
> docker弄好了

linux跑了一小会就429了，哈哈

**Comment by 14790897** [comment]
docker-compose down --volumes --rmi all

docker-compose up -d


删掉重新拉取

**Comment by 14790897** [comment]
那个应该是点赞429

**Comment by lostme01** [comment]
> 那个应该是点赞429

哦，先用docker 跑跑再看
