### ISSUE TITLE
Win/Webstorm 报错

### ISSUE THREAD

**Issue by sst2020** [14790897/auto-read-liunxdo#9]
Win11 22621；Webstorm 2024.1；Node.js v21.6.2.
问题：const usernames = process.env.USERNAMES.split(", ");
                                        ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Object.<anonymous> (F:\hsy\code\auto-read-liunxdo\pteer.js:7:41)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49

Node.js v21.6.2

进程已结束，退出代码为 1
.env为原始状态

**Comment by 14790897** [comment]
npm install了吗
无法读取环境变量应该是你的运行环境有问题

**Comment by sst2020** [comment]
PS \code\auto-read-liunxdo> npm install

up to date in 2s

11 packages are looking for funding
  run `npm fund` for details
PS \code\auto-read-liunxdo> node .\pteer.js
F:\hsy\code\auto-read-liunxdo\pteer.js:7
const usernames = process.env.USERNAMES.split(", ");
                                        ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Object.<anonymous> (F:\hsy\code\auto-read-liunxdo\pteer.js:7:41)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49

Node.js v21.6.2

**Comment by 14790897** [comment]
问gpt吧，我不清楚

**Comment by 14790897** [comment]
怎么样了

**Comment by 14790897** [comment]
可能是执行目录不在仓库目录中的问题

**Comment by sst2020** [comment]
已解决

**Comment by 14790897** [comment]
什么原因呢？我docker里面也碰到了，需要参考一下

**Comment by sst2020** [comment]
检查.env文件中环境变量名与json中是否一致
